### ISSUE TITLE
Inhaltsverzeichnis

### ISSUE THREAD

**Issue by hvoss49** [rolfn/dtk#1]
Vor der allerletzten Seite, also zwischen \listofaddresses und \tableofcontents wird eine leere
Seite eingefügt. Ich kann momentan nicht erkennen, wieso??

**Comment by rolfn** [comment]
Die Seite mit dem Inhaltsverzeichnis ist immer eine linke (gerade) Seite. Wenn die letzte Seite der Autorenliste zufällig ebenfalls eine linke ist, muss eben eine leere Seite folgen.

**Comment by hvoss49** [comment]
Das ist schon klar. Es war nur nicht so in der alten Klasse. Die beiden gehören zum Umschlag, _müssen_ also immer direkt aufeinander folgen.

**Comment by hvoss49** [comment]
Das \cleardoublepage hat für die DTK-klasse keinerlei Bedeutung.

**Comment by rolfn** [comment]
Die Seite mit dem Inhaltsverzeichnis ist immer eine linke (gerade) Seite. Wenn die letzte Seite der Autorenliste zufällig ebenfalls eine linke ist, muss eben eine leere Seite folgen.
