### ISSUE TITLE
TeX4ht-Logo

### ISSUE THREAD

**Issue by rolfn** [rolfn/dtk#10]
In `dtk.cls` steht:
```
\def\tex4ht{\hologo{TeX4ht}}
```
Da müssten wir uns was anderes einfallen lassen.

**Comment by hvoss49** [comment]
Das ist mir komplett entfallen. Wo ist denn das Problem??

**Comment by rolfn** [comment]
Das hättest Du mich vor drei Jahren fragen sollen :unamused:
