### ISSUE TITLE
Zeilenumbruch innerhab des Makros »Makro«

### ISSUE THREAD

**Issue by rolfn** [rolfn/dtk#11]
Es kann sein, dass der Text, der dem Makro `\Makro` übergeben wird, umbrochen wird. Das sieht seltsam aus. Sollten wir da noch eine `\mbox` einfügen? Bei sehr langen Makronamen wäre allerdings ein Umbruch doch wieder ganz gut. Ich bin unsicher ...

Nachtrag: Vielleicht eine Lösung: `\Makro{...}` (ohne Zeilenumbruch) und `\Makro*{...}` (mit Zeilenumbruch)

**Comment by hvoss49** [comment]
Ja, kann man ändern.



Am So., 10. Feb. 2019 um 12:48 Uhr schrieb Rolf Niepraschk <
notifications@github.com>:
