### ISSUE TITLE
Fehlende Felder im Literaturverzeichnis

### ISSUE THREAD

**Issue by wehro** [rolfn/dtk#12]
Die Klasse `dtk` bzw. der mit ihr eingestellte Bibliographiestil ignoriert beim Medientyp `book` die Felder `volume`, `series` und `number`. Diese tauchen nicht in der Literaturliste auf, obwohl sie in der `bib-Datei` vorhanden sind.

**Comment by hvoss49** [comment]
Dafür ist der Typ `mvbook` zuständig.

**Comment by wehro** [comment]
Mit `mvbook` funktioniert das auch nicht.
So wie ich es verstehe, nimmt man `mvbook` auch nur, wenn man ein mehrbändiges Werks als ganzes zitieren will, nicht für einen Einzelband.

**Comment by hvoss49** [comment]
Verstehe, was du meinst. Mit meiner Version (bzw. der `dtk.bbx` aus diesem Repositorium) geht folgendes:

```
\RequirePackage{filecontents}
\begin{filecontents*}{demo.bib}
@book{knuth,
	author={Donald E. Knuth}, 
	title={Computers \& Typesetting},
	volumes= 5,
	series={The art of Computer Programming},
	number = 4,
	publisher={Addison-Wesley}, 
	location={Reading, Mass.}, 
	date={1984/1986},
}
\end{filecontents*}
\documentclass[ngerman]{dtk}
\addbibresource{demo.bib}
\begin{document}	
	Wie schon \textcite{knuth} sagte \ldots
	
\printbibliography
\end{document}
```

<img width="424" alt="image" src="https://user-images.githubusercontent.com/12891199/55665947-c3a7ff00-5847-11e9-8c73-a5ba965ba500.png">

**Comment by wehro** [comment]
Danke, in Bezug auf `series` und `number` ist die Ausgabe erwartungsgemäß. Allerdings fehlt im folgenden Beispiel noch die Ausgabe des Feldes `volume`.

```
\RequirePackage{filecontents}
\begin{filecontents*}{demo.bib}
@book{knuth,
	author={Donald E. Knuth}, 
	title={The TeXBook},
	maintitle={Computers \& Typesetting},
	volume= 1,
	series={The art of Computer Programming},
	number = 4,
	publisher={Addison-Wesley}, 
	location={Reading, Mass.}, 
	date={1984/1986},
}
\end{filecontents*}
\documentclass[ngerman]{dtk}
\addbibresource{demo.bib}
\begin{document}	
	Wie schon \textcite{knuth} sagte \ldots
	
\printbibliography
\end{document}
```

**Comment by hvoss49** [comment]
Das sehe ich nicht so, ein Werk hat mehrere Bände ("volumes" -- Plural, wie in meinem Beispiel), die durch "number"  gezählt werden.  Singular "volume" macht beim Buch keinen Sinn. Aber wenn du das anders haben willst, dann ergänzt du eben die Definition. Nur für die DTK bleibt das so.

**Comment by wehro** [comment]
OK.
