### ISSUE TITLE
dtk-logos 1.07: Use of \BibTeX doesn't match its definition.

### ISSUE THREAD

**Issue by adbrucker** [rolfn/dtk#13]
Hi,
Compiling the following minimal example:
``` latex
\documentclass{article}
\usepackage{dtk-logos}
\begin{document}
  \BibTeX
\end{document}
```

with "dtk-logos 2019/06/05 v. 1.07 Dante Edition: Logos (hv)" results in the error
```
! Use of \BibTeX doesn't match its definition.
```

Best,
Achim

**Comment by hvoss49** [comment]
fixed in https://github.com/rolfn/dtk/commit/d72ce05439f0060b0496ab9e5e8c8f0b13392794
