### ISSUE TITLE
Fehlermeldung bei nicht vorhandener Datei

### ISSUE THREAD

**Issue by hvoss49** [rolfn/dtk#14]
wenn ich in der Hauptdatei beispielsweise

`\Input{Datei_die_nicht_existiert}`

mache, weil ich einen Tippfehler habe, lautet
die Fehlermeldung:

```
[...]
(./dtk-grusswort.tex) (./Ziegenhagen.tex)

! LaTeX Error: File `csnameendcsname.tex' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: tex)

Enter file name:
! Emergency stop.
<read *>

\@missingfileerror ...obal \read \m@ne to\@gtempa
[...]
```

Da das selten passiert, suche ich dann meistens lange,
bis ich mich erinnere, dass ich vielleicht einen
Tippfehler habe. Kann man das leicht zu einer "sprechenden"
Fehlermeldung ändern? Kann auch sein, dass es mit dem
modifizierten \IfFileExists{}{} des letzten LaTeX-Updates
zu tun hat.

**Comment by rolfn** [comment]
Ich hab den Fehler gefunden. Es war ein Test drin, ob die Datei existiert. Nur im positiven Fall blieb der Dateiname erhalten, sonst leer. Das war Unsinn oder zumindest unnötig.
