### ISSUE TITLE
dtk-autoren.ind

### ISSUE THREAD

**Issue by hvoss49** [rolfn/dtk#15]
Wenn ich irgendeine Änderung bei \Author mache, kommt diese nicht in die ind-Datei,
da xindy nicht aufgerufen wird. Erst mit make clean wird sie neu erstellt. Auch wenn ich
dtk-autoren.ind lösche, gibt es mit make all keine neue. Es wäre besser, wenn xindy
einfach _jedesmal_ aufgerufen wird, bzw. mindestens dann, wenn sich dtk-autoren.idx geändert hat.

Die stk-autoren.idx.old ist eigentlich überflüssig.

**Comment by rolfn** [comment]
Ich glaube, dass ich den Fehler gefunden habe. Die Make-Variable `MAX_LTX_RUNS` war zu klein, weshalb ein einzelner make-Aufruf nicht reichte, um auch die Autorenliste zu aktualisieren. Der folgende Test mit der aktuellen Version von `Makefile.in` sollte positiv ausgehen ( `MAX_LTX_RUNS` ist jetzt 4):
```
git pull # letzter Stand von GITHUB
make clean
make

# Ergebnis:
# Hugo Mustermann [4,7]

sed 's/Mustermann/Musterfrau/g' artikel1.tex > zz ; mv zz artikel1.tex
make

# Ergebnis:
# Hugo Musterfrau [4]
# Hugo Mustermann [7]

git reset --hard HEAD # wieder letzter Stand von GITHUB
```
