### ISSUE TITLE
idx-Datei

### ISSUE THREAD

**Issue by hvoss49** [rolfn/dtk#16]
Wenn bei einem Autor der dritte Parameter leer bleibt, dann lautet der Eintrag

`\indexentry{PickertNils@Nils Pickert!\relax }{5}`

Durch `\relax` kommen jetzt aber die Fragezeichen in die Ausgabe. Da ein Autor
grundsätzlich nicht gezwungen wird, etwas anzugeben, sollte entweder:

- statt `\relax` einfach nur ' \null`  
- oder im Makro ein `\relax`  _keine_ Fragezeichen liefern

**Comment by rolfn** [comment]
Die roten Fragezeichen waren gedacht, um auf möglicherweise versehentlich nicht angegebenen dritten Parameter hinzuweisen. Sie erscheinen auch nur bei Klassenoption "korr", also nicht im endgültigen Dokument. Ich gebe aber zu, dass der Nutzen fragwürdig ist, weshalb ich sie nun beseitigt habe. Nebenbei: `MAX_LTX_RUNS` habe ich auf 5 erhöht.

**Comment by hvoss49** [comment]
Sie kamen auch im Enddokument! Sonst hätte mich das ja gar nicht gestört.

Am Fr., 25. Okt. 2019 um 08:03 Uhr schrieb Rolf Niepraschk <
notifications@github.com>:

**Comment by rolfn** [comment]
Das muss an nicht ausreichender Anzahl von LaTeX-Läufen (`MAX_LTX_RUNS`) gelegen haben. Ich testete explizit auf die korr-Angabe bei den Fragezeichen.
