### ISSUE TITLE
\captionbelowskip

### ISSUE THREAD

**Issue by hvoss49** [rolfn/dtk#17]
```
\documentclass[ngerman]{dtk}
\usepackage{blindtext}
\input{dtk-userpackages}

\begin{document}
\blindtext

\begin{figure}[!htb]
\rule{\textwidth}{3cm}
\caption{hier kommt eine Beschriftung}
\end{figure}

\blindtext
\end{document}
```

Obiges Beispiel liefert vernünftige Abstände zwischen Caption und folgendem Text. In der erzeugten dtk sieht das aber ganz anders aus (siehe dtk.pdf  in der Dropbox)

**Comment by rolfn** [comment]
Die Sache scheint aufwändig zu werden, denn der folgende Test brachte mich nicht weiter:
```latex
% captionbelowskip-full.tex
%
\begin{filecontents}{captionbelowskip-test.tex}
\documentclass{dtk}
\usepackage{blindtext}

\begin{document}
\blindtext

\begin{figure}[!htb]
\rule{\textwidth}{3cm}
\caption{hier kommt eine Beschriftung}
\end{figure}

\blindtext
\end{document}
\end{filecontents}
% ----------------------------------------
\documentclass[full]{dtk}
\begin{document}
  \DTKinput{captionbelowskip-test.tex}
\end{document}
```
Die Ausgaben von
```
TEXINPUTS=./texmf: lualatex captionbelowskip-test.tex
```
und
```
TEXINPUTS=./texmf: lualatex captionbelowskip-full.tex
```
sind identisch. Ich werde weiter überlegen. Vielleicht gibt es zusätzlichen Leerraum auf der Seite, der verteilt wird.

**Comment by rolfn** [comment]
Eine Idee dazu. Bitte teste mal Folgendes direkt nach `\begin{document}`:
```latex
\setlength\textfloatsep{0pt}% vorher: 20.0pt plus 2.0pt minus 4.0pt
\setlength\intextsep{0pt}% vorher: 12.0pt plus 2.0pt minus 2.0pt
```
Das Ergebnis wird sicher schlecht sein, aber interessant wäre, ob zumindest mehr Gleichmäßigkeit eintritt. Endgültig könnte man dann z.B. mit
```latex
\setlength\textfloatsep{20.0pt plus .5pt minus .5pt}%
\setlength\intextsep{12.0pt plus .3pt minus .3pt}%   
```
arbeiten, also insbesondere mit weniger Gummianteilen. Vielleicht sollte man aber auch den jeweiligen festen Teil anpassen, denn er kommt mir gefühlsmäßig zu groß vor. Beurteilen kann man das aber erst mit dem Gesamtdokument.

**Comment by hvoss49** [comment]
Hat jetzt zwar den kompletten Umbruch zerhauen, aber es sieht so aus, als sei es _erheblich_ besser.
Ich mach mal ein `make clean` und dann komplett neu `make`

Ergebnis: ERHEBLICH besser!

**Comment by hvoss49** [comment]
```
\setlength\textfloatsep{20.0pt plus .5pt minus .5pt}%
\setlength\intextsep{12.0pt plus .3pt minus .3pt}%   
```

Die bewirken nicht wirklich etwas. Alles merkwürdig ...

**Comment by rolfn** [comment]
Wie wär's damit?
```latex
\setlength\textfloatsep{10.0pt plus 1pt minus 1pt}%
\setlength\intextsep{6.0pt plus .5pt minus .5pt}%   
```

**Comment by rolfn** [comment]
> ```
> \setlength\textfloatsep{20.0pt plus .5pt minus .5pt}%
> \setlength\intextsep{12.0pt plus .3pt minus .3pt}%   
> ```
> 
> Die bewirken nicht wirklich etwas. Alles merkwürdig ...

Nicht ausgeschlossen, dass man
```latex
\AtBeginDocument{%
  \setlength\textfloatsep{20.0pt plus .5pt minus .5pt}%
  \setlength\intextsep{12.0pt plus .3pt minus .3pt}%
}
```
oder so machen muss.

**Comment by hvoss49** [comment]
HAbe jetzt 

```
\setlength\textfloatsep{10.0pt plus 1pt minus 1pt}%
\setlength\intextsep{6.0pt plus .5pt minus .5pt}%  
```

was zu einer befriedigenden Ausgabe führt.

**Comment by rolfn** [comment]
Gut. Ich hab's eingefügt und schließe.
