### ISSUE TITLE
`Font "LatinModernMath-Regular" cannot be found` error in MWE

### ISSUE THREAD

**Issue by Mo-Gul** [rolfn/dtk#18]
A simple
```latex
\documentclass{dtk}
\begin{document}
    test
\end{document}
```
leads to the error
```
! Package fontspec Error: The font "LatinModernMath-Regular" cannot be found.

For immediate help type H <return>.
 ...                                              
                                                  
l.31   \setmathfont
                 [version=XITS]{XITSMath-Regular.otf}
```
when compiling with LuaLaTeX with an up-to-date MiKTeX. Is that intended and one has to install this font manually? If yes, how?

**Comment by hvoss49** [comment]
Install the Latin Modern (Math) with MikTeX’s package manager

Herbert

**Comment by Mo-Gul** [comment]
Hmm, searching for "latin modern" yields no results.
Searching for "latin" yields maybe `newcomputermodern`.
Searching for "modern" additionally yields maybe `mlmodern`.
Is that one of the required packages? If not, could you state the correct (full) name of the required package, please?

**Comment by hvoss49** [comment]
> Am 29.07.2021 um 10:08 schrieb Mo-Gul ***@***.***>:
> 
> 
> Hmm, searching for "latin modern" yields no results.
> Searching for "latin" yields maybe newcomputermodern.
> Searching for "modern" additionally yields maybe mlmodern.
> Is that one of the required packages? If not, could you state the correct (full) name of the required package, please?


Package lm-math

Herbert

**Comment by Mo-Gul** [comment]
Thank you very much. Please consider adding this with `RequirePackage` (or whatever is suitable) to the `dtk` package.

**Comment by hvoss49** [comment]
Mo-Gul ***@***.***> schrieb am Do. 29. Juli 2021 um 18:52:

> Thank you very much. Please consider adding this with RequirePackage (or
> whatever is suitable) to the dtk package.
>


Unicode-Math expects a defined math font. If you do not have that one
installed,
you‘ll get an error. No chance for the dtk.cls to check this.

Herbert
