### ISSUE TITLE
"wrong"/suboptimal definitions of `\eV` and `\dante`?

### ISSUE THREAD

**Issue by Mo-Gul** [rolfn/dtk#19]
I guess the definitions of 

https://github.com/rolfn/dtk/blob/bd25fdd6706695df47928fcb107c49f3078e4ca1/texmf/dtk-logos.sty#L139-L140

are "wrong". The MWE

```latex
\documentclass[border=5pt,varwidth]{standalone}
\makeatletter
    \providecommand\eV{e.V\kern-0.18em\@ifnextchar.{}{.}\kern0.18em}
    \providecommand\dante{\mbox{DANTE~\eV}}
\makeatother
\begin{document}
        \noindent%
    \dante{}. \\
    \dante{},
\end{document}
```

yields

![result with "wrong" definitions](https://user-images.githubusercontent.com/17992976/127446074-18c29a20-9d02-4149-9687-9f5e1aee7f90.png)

1. I think there should be no extra space between two punctuation signs, thus the second `\kern` should be superfluous.
2. I think the first `\dante` line in the document shows two dots because "DANTE" is inside an `\mbox` which doesn't allow the `\eV` definition to see the next char (with `\@ifnextchar`).

Some time ago for a problem that I cannot remember any more I found <https://stackoverflow.com/a/3285603/5776000> and after some tweaking with Joseph (Wright) we/he came up with

```latex
\documentclass[border=5pt,varwidth]{standalone}
\usepackage{xspace}
%% if a dot follows the commands xspace can't do something about it
%% it follows an approach from Joseph Wright with the `expl3` package
%% from <https://stackoverflow.com/questions/3282319/correct-way-to-define-macros-etc-ie-in-latex>
%% (with some extensions done together with Joseph via email)
\ExplSyntaxOn
\NewDocumentCommand{\latinabbrev}{m}{
  \peek_meaning_remove:NTF .
    { #1 \@. }
    { #1 .\@ \xspace }
}
\ExplSyntaxOff
%Omit final dot from each def.
\NewDocumentCommand\eV{}{\latinabbrev{e.V}}
\NewDocumentCommand\dante{}{DANTE~\eV}
\begin{document}
        \noindent%
    \dante. \\
    \dante, \\
    \dante is the best!
\end{document}
```

which yields

![result with "better" definitions](https://user-images.githubusercontent.com/17992976/127454380-69bce2c0-3e0d-494b-ac77-abcc3135cb7f.png)

Maybe this approach can be adapted for the needs here?

**Comment by hvoss49** [comment]
> Am 29.07.2021 um 10:02 schrieb Mo-Gul ***@***.***>:
> 
> 
> I guess the definitions of
> 
> https://github.com/rolfn/dtk/blob/bd25fdd6706695df47928fcb107c49f3078e4ca1/texmf/dtk-logos.sty#L139-L140
> 
> are "wrong". The MWE
> 
> \documentclass[border=5pt,varwidth]{standalone}
> \makeatletter
> ***@***.***{}{.}\kern0.18em}
> \providecommand\dante{\mbox{DANTE~\eV}}
> \makeatother
> \begin{document}
> \noindent%
> \dante{}. \\


That is wrong input … 

However, I can insert a check for a following dot 

Herbert

**Comment by hvoss49** [comment]
```latex
\documentclass[border=5pt,varwidth]{standalone}
\usepackage{xspace}
\makeatletter
\def\d@nte{\@ifnextchar.%
  {\mbox{DANTE e.\kern-0.1em V\kern-0.18em}}% 
  {\mbox{DANTE e.\kern-0.1em V\kern-0.18em.}\xspace}% 
}
\def\dante#1{%
  \ifx#1\@empty
     \d@nte 
  \else
     \expandafter\d@nte#1% 
  \fi}
\makeatother

\begin{document}
\noindent%
\dante{}.\\   
\dante{},\\   
\dante. \\
\dante, \\
\dante is the best!

\end{document}
```

**Comment by Mo-Gul** [comment]
Unfortunately, your email client seems to mask stuff that contains an `@` ...
Otherwise I think you have noticed yourself that with the original code an input in the document of `\dante{}` or doesn't `\dante` yields the same output.

**Comment by hvoss49** [comment]
> Am 29.07.2021 um 18:48 schrieb Mo-Gul ***@***.***>:
> 
> 
> Unfortunately, your email client seems to mask stuff that contains an @ ...


Oh …
See edit

**Comment by Mo-Gul** [comment]
Much better. Just for a reference, here the result of [above code](https://github.com/rolfn/dtk/issues/19#issuecomment-889003845).

![result of referenced code](https://user-images.githubusercontent.com/17992976/127534234-b4070c01-792b-4aa0-b5af-579b96ac8ca6.png)

**Comment by Mo-Gul** [comment]
Do you want to merge your [new definition of `\dante`](https://github.com/rolfn/dtk/issues/19#issuecomment-889003845) and release a new version on CTAN, so it is directly used for the next issue? Shall I provide a pull request with your definition?

**Comment by hvoss49** [comment]
`dtk-logos.sty` is removed from `dtk`  and will be replaced by `hvlogos`
