### ISSUE TITLE
gobbled spaces (and lines) when first line is indented

### ISSUE THREAD

**Issue by Mo-Gul** [rolfn/dtk#21]
When using `dtk` document class characters/lines seem to be gobbled up to the first non-whitespace character. Is this intended and how can this be avoided, in case one _wants_ the indention?

```tex
\documentclass{standalone}
\usepackage{listings}
\begin{document}
\begin{lstlisting}[name=lua]
          if n.penalty ~= 10000 then
            only_characters = false
          end
        end
      end
    end
\end{lstlisting}
\end{document}
```

gives the output on the left (without the frame which was added to show that the starting spaces are kept) and replacing the document class with `dtk` gives the output on the right.

![grafik](https://github.com/rolfn/dtk/assets/17992976/7955ac94-3c24-4176-bd15-161eed13f676)

**Comment by rolfn** [comment]
This was intentional in the past because the `dtk` class automatically loaded the `lstautogobble` package. This will no longer happen in the next version.
