### ISSUE TITLE
dtk 2023/12/01v2.10cdtk yields error message

### ISSUE THREAD

**Issue by schneeschmelze** [rolfn/dtk#24]
I'm afraid I cannot compile my regular contribution to DTK journal (or any other file using `dtk.cls`) properly. LuaLaTeX produces a PDF file, but compilation stops with: 

`ERROR: LaTeX Error: Command \maketitle already defined.`

Error tracking in AUCTeX sends me to `scrbook.cls`, but after consulting Markus we think that probably `hyperref.sty` should better be loaded later in `dtk.cls`. Probably, it would be better to load `\RequirePackage{dtk-url}`after loading `scrbook.cls`. Anyway, the latest update to the files in question happend to `hyperref.sty` — that was after I last touched upon my files using `dtk.cls`.

Could you please take a look into this? – Thanks in advance!

**Comment by hvoss49** [comment]
Das ist wohl ein Problem mit `hvqrurl` und `hyperref`. Da muss ich nachsehen ...

**Comment by hvoss49** [comment]
Habe eine Lösung, muss sie aber erst nochmal mit Rolf durchgehen.

**Comment by schneeschmelze** [comment]
Vielen Dank für deine schnelle Hilfe!

**Comment by rolfn** [comment]
Mit der Version 2.10d ist der Fehler korrigiert. In Kürze auch auf CTAN.
