### ISSUE TITLE
Fehlermeldung mit \Paket-Befehl in Abschnittsüberschrift

### ISSUE THREAD

**Issue by wehro** [rolfn/dtk#25]
Wenn der Befehl `\Paket` in einer Abschnittsüberschrift eingesetzt wird, kommt eine Fehlermeldung.
```
\documentclass{dtk}
\begin{document}
\section{Das Paket \Paket{babel}}
\end{document}
```

```
! Use of \\bookmark doesn't match its definition.
\t@st@ic ...ed@b \expandafter =\reserved@a \relax 
                                                  \ifx \reserved@b \@let@tok...

l.3 \section{Das Paket \Paket{babel}}
```

**Comment by hvoss49** [comment]
mach 
```
section{Das Paket \noexpand\Paket{babel}}
```

Müssen wir genauer nachsehen, warum hyperref/bookmark jetzt kein `\let\Paket\texttt`  mehr mag ...

**Comment by hvoss49** [comment]
Folgendes hat denselben Fehler, womit es nichts mit der DTK zu tun hat ...

```
\listfiles
%\DocumentMetadata{}
\documentclass{article}
\usepackage[ngerman]{babel}
\usepackage{hyperref}
\let\Paket\texttt
\begin{document}
	\section{Das Paket %\noexpand
		\Paket{babel}}
\end{document}
```

**Comment by rolfn** [comment]
In Version 2.10e sind jetzt `\Paket` und weitere Makros rubust, sodass das Problem nicht mehr auftritt (kein `\noexpand` mehr nötig). Die neue Version wird in Kürze auf CTAN verfügbar sein.
