### ISSUE TITLE
Fehlendes Makro für Dateinamen

### ISSUE THREAD

**Issue by wehro** [rolfn/dtk#26]
Die Anleitung `beispiel.pdf` erwähnt gleich zu Beginn die Definition `\DeclareUrlCommand\File{\urlstyle{tt}}`.
Ein solcher Befehl wird aber von `dtk.cls` gar nicht definiert. Die Verwendung von `\File` ergibt:
`! Undefined control sequence.`

**Comment by hvoss49** [comment]
mach mal ein TeX-Live Update. Steht dann am Anfang von `beispiel.tex` folgendes?

```
\let\File\texttt
\let\Package\texttt

```

**Comment by wehro** [comment]
Ja, steht da.
Allein: was nützt’s? Das müsste nach `dtk.cls`.

**Comment by hvoss49** [comment]
Schon klar, habe mich nur gewundert, warum es bei mir keine Fehler gab.

Ist jetzt in dtv-url ergänzt.
