### ISSUE TITLE
Schriftproblem mit pgf-PeriodicTable

### ISSUE THREAD

**Issue by wehro** [rolfn/dtk#27]
Das folgende Beispiel wird in _Computer Modern_ statt _Libertinus Serif_ ausgegeben:
```
\documentclass{dtk}
\usepackage{pgf-PeriodicTable}
\usepackage{blindtext}
\begin{document}
\blindtext
\end{document}
```
![Ausgabe](https://github.com/user-attachments/assets/3ff080ba-f066-4b53-9e24-24622dd17288)

Möglicherweise liegt das Problem beim Paket `pgf-PeriodicTable`. Zu bedenken ist jedoch, dass die Ausgabe des folgenden Beispiels korrekt in _Libertinus Serif_ erfolgt.
```
\documentclass{article}
\usepackage{libertinus}
\usepackage{pgf-PeriodicTable}
\usepackage{blindtext}
\begin{document}
\blindtext
\end{document}
```
Ich bitte daher um eine Prüfung.

**Comment by hvoss49** [comment]
Aus meiner Sicht ein Problem mit pdf-PeriodicTable, da er ziemlich viel und ohne Not an der
Schriftsetzung "rumspielt".

Mach

```
\documentclass{dtk}
\usepackage{pgf-PeriodicTable}
\setmainfont{LibertinusSerif-Regular.otf}
\usepackage{blindtext}
\begin{document}
\blindtext
\end{document}

```

**Comment by hvoss49** [comment]
Das hier ist aus meiner Sicht das Problem (ab Zeile 19 in `pgf-PeriodicTable.sty)`:

```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% check the engine and load font packages
\ifx\pdfliteral\undefined\relax% XeLaTeX or LuaLaTeX
  \RequirePackage{fontspec}[2020/02/03]\edef\pgfPT@fontspec{1}%
\else% pdfLaTeX
  \RequirePackage[T1]{fontenc}\edef\pgfPT@fontspec{0}%
\fi%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

`\pdfliteral`  ist für `lualatex` definiert und nicht wie oben angenommen `\undefined`, weshalb dann für `lualatex` eine falsche Schriftsetzung erfolgt.  Kommentiert man obiges komplett aus, dann funktioniert es. Das Paket sollte ohnehin _ausschließlich_  mit `\sffamily`, `\rmfamily`, usw.  arbeiten und nicht selber Schriften setzen.

**Comment by wehro** [comment]
Danke, ich gebe das an den Paketautor weiter.

**Comment by wehro** [comment]
Ist jetzt in `pgf-PeriodicTable` korrigiert.
