### ISSUE TITLE
Biber-Warnung

### ISSUE THREAD

**Issue by rolfn** [rolfn/dtk#5]
"`Please (re)run Biber on the file:`"wird auch bei Nichtverwendung bibliografischer Angaben ausgeschrieben.

**Comment by rolfn** [comment]
Das beschriebene Problem tritt gar nicht auf.

**Comment by hvoss49** [comment]
Doch, das "Problem" tritt immer dann auf, wenn man einen einzelnen Artikel übersetzen will. Und hierbei auch nur beim ersten Durchlauf.

**Comment by rolfn** [comment]
Na, gut. Dann betrachten wir es einfach doch als belanglos.
