### ISSUE TITLE
Zeilennummern

### ISSUE THREAD

**Issue by rolfn** [rolfn/dtk#6]
Um zu vermeiden, dass Zeilennummern in der Korrekturphase den Umbruch beinflussen (wie es das derzeit verwendete Paket tut), könnte man die Zeilennummern statisch quasi als Grafik in den Rand schreiben. Zwar gäbe es dann keine ganz genaue Zuordnung mehr zu einer wirklichen Zeile, aber ungefähr würde es stimmen und wäre wohl ausreichend für die Orientierung.

**Comment by hvoss49** [comment]
Rolf Niepraschk schrieb:

> Um zu vermeiden, dass Zeilennummern in der Korrekturphase den Umbruch
> beinflussen (wie es das derzeit verwendete Paket tut), könnte man die
> Zeilennummern statisch quasi als Grafik in den Rand schreiben. Zwar gäbe
> es dann keine ganz genaue Zuordnung mehr zu einer wirklichen Zeile, aber
> ungefähr würde es stimmen und wäre wohl ausreichend für die Orientierung.

aber das ändert ja nichts an der Vorgehensweise: Irgendwann
muss ich die dtk ohne darstellen und wenn dann ein kurzer
Artikel kommt, schalte ich sie ja nicht extra wieder
ein.

Herbert

**Comment by rolfn** [comment]
aber das ändert ja nichts an der Vorgehensweise: Irgendwann
muss ich die dtk ohne darstellen und wenn dann ein kurzer
Artikel kommt, schalte ich sie ja nicht extra wieder
ein.

Warum nicht? Auch dann ist es zum Korrigieren besser, wenn man genaue Koordinaten angibt. Und es kommen ja auch noch gelegentlich längere Artikel recht spät oder einem Lektor fällt zu einem eigentlich schon korrigierten Artikel doch noch was ein o.ä.

...Rolf

**Comment by hvoss49** [comment]
Rolf Niepraschk schrieb:

> aber das ändert ja nichts an der Vorgehensweise: Irgendwann
> muss ich die dtk ohne darstellen und wenn dann ein kurzer
> Artikel kommt, schalte ich sie ja nicht extra wieder
> ein.
> 
> Warum nicht? Auch dann ist es zum Korrigieren besser, wenn man genaue
> Koordinaten angibt. Und es kommen ja auch noch gelegentlich längere
> Artikel recht spät oder einem Lektor fällt zu einem eigentlich schon
> korrigierten Artikel doch noch was ein o.ä.

weil irgendwann ja ohnehin längere Zeit _ohne_ Zeilennummern
gearbeitet werden muss. Das will ich ja nicht alleine
kontrollieren.

Herbert

**Comment by hvoss49** [comment]
Am 28.10.2016 um 14:30 schrieb Rolf Niepraschk:

> aber das ändert ja nichts an der Vorgehensweise: Irgendwann
> muss ich die dtk ohne darstellen und wenn dann ein kurzer
> Artikel kommt, schalte ich sie ja nicht extra wieder
> ein.
> 
> Warum nicht? Auch dann ist es zum Korrigieren besser, wenn man genaue
> Koordinaten angibt. Und es kommen ja auch noch gelegentlich längere
> Artikel recht spät oder einem Lektor fällt zu einem eigentlich schon
> korrigierten Artikel doch noch was ein o.ä.

kann man denn die Zeilennummern, so wie sie jetzt sind,
nicht einfach in eine \vbox der Höhe 0pt packen?

Herbert

**Comment by rolfn** [comment]
Am 28.10.2016 um 20:41 schrieb hvoss49:

> Am 28.10.2016 um 14:30 schrieb Rolf Niepraschk:
> 
> > aber das ändert ja nichts an der Vorgehensweise: Irgendwann
> > muss ich die dtk ohne darstellen und wenn dann ein kurzer
> > Artikel kommt, schalte ich sie ja nicht extra wieder
> > ein.
> > 
> > Warum nicht? Auch dann ist es zum Korrigieren besser, wenn man genaue
> > Koordinaten angibt. Und es kommen ja auch noch gelegentlich längere
> > Artikel recht spät oder einem Lektor fällt zu einem eigentlich schon
> > korrigierten Artikel doch noch was ein o.ä.
> 
> kann man denn die Zeilennummern, so wie sie jetzt sind,
> nicht einfach in eine \vbox der Höhe 0pt packen?

Vielleicht, sicher bin ich mir aber nicht. Ich bin mir auch nicht 
sicher, ob es was nützen würde. Die ganze Mechanerie, die das Paket 
"lineno" aufbaut ist sehr kompliziert und für mich undurchsichtig. Ich 
halte es für besser, auf "lineno" zu verzichten und so eine Art 
"festgenageltes Lineal" im Randbereich sichtbar zu machen. Damit gäbe es 
ganz sicher keine Beeinflussung des Fließtextes mehr.

...Rolf
