### ISSUE TITLE
Add a CTAN package info for dtk-logos

### ISSUE THREAD

**Issue by koppor** [rolfn/dtk#9]
dtk-logos was recommended at https://tex.stackexchange.com/a/18106/9075 (as `dtklogos`). For some packages (such as [scrlayer-scrpage](https://www.ctan.org/pkg/scrlayer-scrpage)), there is a separate CTAN page even though it is distributed within another package. Would it be possible to create a CTAN entry for dtk-logos?

**Comment by hvoss49** [comment]
no, nearly all stuff is now in `hvlogos.sty` which should be used instead.
